<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->delete();

        DB::table('products')->insert([
            ['category' => 'Entradas', 'name' => 'Papas Fritas simples', 'price' => 10000.00],
            ['category' => 'Entradas', 'name' => 'Papas Fritas gratinadas', 'price' => 13000.00],
            ['category' => 'Entradas', 'name' => 'Mandioca Frita', 'price' => 15000.00],
            ['category' => 'Entradas', 'name' => 'Rabas', 'price' => 17000.00],
            ['category' => 'Entradas', 'name' => 'Bastones de Muzzarela', 'price' => 14500.00],
            ['category' => 'Entradas', 'name' => 'Papas Fritas Los Troncos', 'price' => 9000.00],
            ['category' => 'Entradas', 'name' => 'Ensalada César', 'price' => 12000.00],

            ['category' => 'Picadas', 'name' => 'Para 2 personas', 'price' => 26000.00],
            ['category' => 'Picadas', 'name' => 'Para 4 personas', 'price' => 38000.00],
            ['category' => 'Picadas', 'name' => 'Para 6 personas', 'price' => 48000.00],

            ['category' => 'Empanadas', 'name' => 'Jamón y Queso', 'price' => 1600.00],
            ['category' => 'Empanadas', 'name' => 'Capresse', 'price' => 1600.00],
            ['category' => 'Empanadas', 'name' => 'Carne Molida', 'price' => 1600.00],
            ['category' => 'Empanadas', 'name' => 'Cebolla y Queso', 'price' => 1600.00],
            ['category' => 'Empanadas', 'name' => 'Pollo', 'price' => 1600.00],
            ['category' => 'Empanadas', 'name' => 'Verdura', 'price' => 1600.00],
            ['category' => 'Empanadas', 'name' => 'Humita', 'price' => 1600.00],
            ['category' => 'Empanadas', 'name' => 'Roquefort y Nueces', 'price' => 1900.00],
            ['category' => 'Empanadas', 'name' => 'Cuatro Quesos', 'price' => 1800.00],
            ['category' => 'Empanadas', 'name' => 'Jamón Crudo y Mozza', 'price' => 1800.00],
            ['category' => 'Empanadas', 'name' => 'Árabe', 'price' => 1800.00],
            ['category' => 'Empanadas', 'name' => 'Carne a Cuchillo', 'price' => 2000.00],
            ['category' => 'Empanadas', 'name' => 'Panceta', 'price' => 1900.00],

            ['category' => 'Sándwiches', 'name' => 'Loro Negro', 'price' => 14000.00],
            ['category' => 'Sándwiches', 'name' => 'Guatembú Blanco', 'price' => 14000.00],
            ['category' => 'Sándwiches', 'name' => 'Angelim Rojo', 'price' => 15000.00],
            ['category' => 'Sándwiches', 'name' => 'Los Troncos', 'price' => 15000.00],
            ['category' => 'Sándwiches', 'name' => 'Ibirá', 'price' => 14000.00],
            ['category' => 'Sándwiches', 'name' => 'Guayubira', 'price' => 12000.00],
            ['category' => 'Sándwiches', 'name' => 'Mediterráneo', 'price' => 12000.00],
            ['category' => 'Sándwiches', 'name' => 'Tostado', 'price' => 7000.00],
            ['category' => 'Sándwiches', 'name' => 'Tostado gratinado', 'price' => 9000.00],

            ['category' => 'Hamburguesas', 'name' => 'Lapacho Negro', 'price' => 8500.00],
            ['category' => 'Hamburguesas', 'name' => 'Cedro Misionero', 'price' => 9500.00],
            ['category' => 'Hamburguesas', 'name' => 'Araucaria', 'price' => 10500.00],
            ['category' => 'Hamburguesas', 'name' => 'Cancharana', 'price' => 10000.00],
            ['category' => 'Hamburguesas', 'name' => 'María Preta', 'price' => 11000.00],
            ['category' => 'Hamburguesas', 'name' => 'Laurel Negro', 'price' => 11000.00],
            ['category' => 'Hamburguesas', 'name' => 'Tacuarembó', 'price' => 12000.00],
            ['category' => 'Hamburguesas', 'name' => 'Chicken Burger', 'price' => 9500.00],
            ['category' => 'Hamburguesas', 'name' => 'Kid Burger', 'price' => 7000.00],
            ['category' => 'Hamburguesas', 'name' => 'Veggie Los Troncos', 'price' => 7500.00],

            ['category' => 'Pizzas', 'name' => 'Timbó', 'price' => 13000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Timbó', 'price' => 6500.00],
            ['category' => 'Pizzas', 'name' => 'Palo Rosa', 'price' => 15000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Palo Rosa', 'price' => 7500.00],
            ['category' => 'Pizzas', 'name' => 'Palmito', 'price' => 16000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Palmito', 'price' => 8000.00],
            ['category' => 'Pizzas', 'name' => 'Caña Fístola', 'price' => 18000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Caña Fístola', 'price' => 9000.00],
            ['category' => 'Pizzas', 'name' => 'Anchico', 'price' => 17000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Anchico', 'price' => 8500.00],
            ['category' => 'Pizzas', 'name' => '4 Quesos', 'price' => 17000.00],
            ['category' => 'Pizzas', 'name' => '1/2 4 Quesos', 'price' => 8500.00],
            ['category' => 'Pizzas', 'name' => 'Petiribí', 'price' => 15000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Petiribí', 'price' => 7500.00],
            ['category' => 'Pizzas', 'name' => 'Ananá', 'price' => 17000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Ananá', 'price' => 8500.00],
            ['category' => 'Pizzas', 'name' => 'Pindó', 'price' => 15000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Pindó', 'price' => 7500.00],
            ['category' => 'Pizzas', 'name' => 'Kurupí', 'price' => 19000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Kurupí', 'price' => 9500.00],
            ['category' => 'Pizzas', 'name' => 'Urunday', 'price' => 17000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Urunday', 'price' => 8500.00],
            ['category' => 'Pizzas', 'name' => 'Araticú', 'price' => 21000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Araticú', 'price' => 10500.00],
            ['category' => 'Pizzas', 'name' => 'Champiñones', 'price' => 18000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Champiñones', 'price' => 9000.00],
            ['category' => 'Pizzas', 'name' => 'Carandaí', 'price' => 14000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Carandaí', 'price' => 7000.00],
            ['category' => 'Pizzas', 'name' => 'Mora Blanca', 'price' => 14000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Mora Blanca', 'price' => 7000.00],
            ['category' => 'Pizzas', 'name' => 'Incienso', 'price' => 13000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Incienso', 'price' => 6500.00],
            ['category' => 'Pizzas', 'name' => 'Los Troncos', 'price' => 18000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Los Troncos', 'price' => 9000.00],
            ['category' => 'Pizzas', 'name' => 'Hambur Pizza', 'price' => 26000.00],
            ['category' => 'Pizzas', 'name' => '1/2 Hambur Pizza', 'price' => 13000.00],

            ['category' => 'Milanesas', 'name' => 'De Ternera', 'price' => 13000.00],
            ['category' => 'Milanesas', 'name' => 'A Caballo', 'price' => 14000.00],
            ['category' => 'Milanesas', 'name' => 'Napolitana', 'price' => 15500.00],
            ['category' => 'Milanesas', 'name' => 'A la Suiza', 'price' => 16000.00],
            ['category' => 'Milanesas', 'name' => 'Agridulce', 'price' => 16000.00],
            ['category' => 'Milanesas', 'name' => 'Marinera', 'price' => 15000.00],
            ['category' => 'Milanesas', 'name' => 'Los Troncos', 'price' => 16000.00],
            ['category' => 'Milanesas', 'name' => 'Desbordé XXL', 'price' => 20000.00],

            ['category' => 'Carnes', 'name' => 'Lomo al Champiñón', 'price' => 16000.00],
            ['category' => 'Carnes', 'name' => 'Lomo a la Mostaza', 'price' => 16000.00],
            ['category' => 'Carnes', 'name' => 'Lomo a la Pimienta', 'price' => 16000.00],
            ['category' => 'Carnes', 'name' => 'Lomo a la Plancha', 'price' => 16000.00],
            ['category' => 'Carnes', 'name' => 'Lomo a la Suiza', 'price' => 16000.00],
            ['category' => 'Carnes', 'name' => 'Bife de Chorizo', 'price' => 16000.00],

            ['category' => 'Milanesas de pescado', 'name' => 'De Merluza', 'price' => 10000.00],
            ['category' => 'Milanesas de pescado', 'name' => 'De Merluza Napolitana', 'price' => 12000.00],
            ['category' => 'Milanesas de pescado', 'name' => 'De Merluza al Roquefort', 'price' => 13000.00],

            ['category' => 'Guarniciones', 'name' => 'Papas Fritas', 'price' => 4000.00],
            ['category' => 'Guarniciones', 'name' => 'Mandioca Frita', 'price' => 4000.00],
            ['category' => 'Guarniciones', 'name' => 'Puré de Papa', 'price' => 4000.00],
            ['category' => 'Guarniciones', 'name' => 'Puré Mixto', 'price' => 4000.00],
            ['category' => 'Guarniciones', 'name' => 'Ensalada Mixta', 'price' => 4000.00],

            ['category' => 'Pastas', 'name' => 'Tallarines', 'price' => 10000.00],
            ['category' => 'Pastas', 'name' => 'Sorrentinos', 'price' => 14000.00],
            ['category' => 'Pastas', 'name' => 'Ravioles', 'price' => 13000.00],
            ['category' => 'Pastas', 'name' => 'Ñoquis de Papa', 'price' => 13000.00],
            ['category' => 'Pastas', 'name' => 'Pastel de Papa', 'price' => 14000.00],
            ['category' => 'Pastas', 'name' => 'Canelones', 'price' => 14000.00],

            ['category' => 'Salsas', 'name' => 'Bolognesa', 'price' => 4500.00],
            ['category' => 'Salsas', 'name' => 'Bechamel', 'price' => 4500.00],
            ['category' => 'Salsas', 'name' => '4 Quesos', 'price' => 4500.00],
            ['category' => 'Salsas', 'name' => 'Roja', 'price' => 4500.00],

            ['category' => 'Vinos', 'name' => 'DV Catena', 'price' => 18000.00],
            ['category' => 'Vinos', 'name' => 'Angélica Zapata', 'price' => 30000.00],
            ['category' => 'Vinos', 'name' => 'Bramare', 'price' => 40000.00],
            ['category' => 'Vinos', 'name' => 'Mosquita Muerta', 'price' => 19000.00],
            ['category' => 'Vinos', 'name' => 'El Enemigo', 'price' => 30000.00],
            ['category' => 'Vinos', 'name' => 'Gran Enemigo', 'price' => 68000.00],
            ['category' => 'Vinos', 'name' => 'Latitud 33 Malbec', 'price' => 10000.00],
            ['category' => 'Vinos', 'name' => 'Santa Julia Malbec', 'price' => 10000.00],
            ['category' => 'Vinos', 'name' => 'Santa Julia Dulce Tinto Natural', 'price' => 10000.00],
            ['category' => 'Vinos', 'name' => 'Santa Julia Blanco Chenin Dulce Natural', 'price' => 10000.00],
            ['category' => 'Vinos', 'name' => 'Trumpeter Malbec', 'price' => 13000.00],

            ['category' => 'Sin alcohol', 'name' => 'Coca-Cola - Sprite - Fanta 1,5 LT', 'price' => 4500.00],
            ['category' => 'Sin alcohol', 'name' => 'Coca-Cola - Sprite - Fanta 1 L', 'price' => 3000.00],
            ['category' => 'Sin alcohol', 'name' => 'Coca-Cola - Sprite - Fanta 500 ML', 'price' => 3500.00],
            ['category' => 'Sin alcohol', 'name' => 'Levité - Agua Mineral 500 ML', 'price' => 2000.00],
            ['category' => 'Sin alcohol', 'name' => 'Limonada', 'price' => 7000.00],
            ['category' => 'Sin alcohol', 'name' => 'Limonada con menta y jengibre', 'price' => 7000.00],

            ['category' => 'Cervezas', 'name' => 'Stella Artois', 'price' => 7500.00],
            ['category' => 'Cervezas', 'name' => 'Corona 710 ML', 'price' => 7000.00],
            ['category' => 'Cervezas', 'name' => 'Corona 330 ML', 'price' => 4500.00],
            ['category' => 'Cervezas', 'name' => 'Quilmes Original', 'price' => 6000.00],
            ['category' => 'Cervezas', 'name' => 'Quilmes Stout', 'price' => 6000.00],
            ['category' => 'Cervezas', 'name' => 'Patagonia', 'price' => 7000.00],
            ['category' => 'Cervezas', 'name' => 'Brahma', 'price' => 6000.00],
            ['category' => 'Cervezas', 'name' => 'Budweiser', 'price' => 4500.00],
            ['category' => 'Cervezas', 'name' => 'Patagonia Lata Bohemian Pilsener', 'price' => 6500.00],
            ['category' => 'Cervezas', 'name' => 'Patagonia Lata Amber Lager', 'price' => 4500.00],
            ['category' => 'Cervezas', 'name' => '24.7', 'price' => 4500.00],

            ['category' => 'Tragos', 'name' => 'Aperol', 'price' => 6500.00],
            ['category' => 'Tragos', 'name' => 'Fernet', 'price' => 6000.00],
            ['category' => 'Tragos', 'name' => 'Fernet XL', 'price' => 10000.00],
            ['category' => 'Tragos', 'name' => 'Gancia', 'price' => 6000.00],
            ['category' => 'Tragos', 'name' => 'Cuba Libre', 'price' => 6500.00],
            ['category' => 'Tragos', 'name' => 'Gin Tonic', 'price' => 6000.00],
            ['category' => 'Tragos', 'name' => 'Campari', 'price' => 6500.00],
            ['category' => 'Tragos', 'name' => 'Vermut', 'price' => 6000.00],
            ['category' => 'Tragos', 'name' => 'Caipiriña', 'price' => 6000.00],
            ['category' => 'Tragos', 'name' => 'Daikiri', 'price' => 6000.00],
            ['category' => 'Tragos', 'name' => 'Gin Tonic frutos rojos', 'price' => 6500.00],
        ]);
    }
}
